### ISSUE TITLE
[question] differences with the original?

### ISSUE THREAD

**Issue by dbuezas** [pecostm32/FNIRSI_1013D_Firmware#1]
I'm having a hard time deciding if I should try your firmware, and can't find information on how it compares to the original.

I'm annoyed at the fact that the trigger and measurements disappear at slow sample rates, and that the time scale can't be changed on a stopped screen.

Great feat reverse engineering the device, regardless of any changes (or lack thereof) you may have made to it.

Thanks!

**Comment by gin66** [comment]
Sorry. I cannot give you a detailed comparison. As per installation/doc you could revert to the original status without worries. For me: I just have installed it couple of months ago and never looked back. Feels like a much better device now. 

Just my 2 cents.

**Comment by dbuezas** [comment]
Gotcha, if it's not the same as the original I'll have to try it now :)
Thanks

**Comment by pecostm32** [comment]
Take a look here: https://www.eevblog.com/forum/testgear/fnirsi-1013d-100mhz-tablet-oscilloscope/msg4049509/#msg4049509
It summarizes the improvements.
There are also some downsides like jitter in the measurements and lacking the FFT. It does need some filtering for the measurements and also the trace display can do with improvements, but I needed a change of scenery and moved on to other projects.

**Comment by dbuezas** [comment]
Finally decided to give it a try through a mac. In the end I had to take the sd card out but it was my mistake.
I still need to test it more thoroughly but I did notice that the rolling mode is gone. That one I'll miss :) 

Anyway, thanks for the links
