### ISSUE TITLE
Magenta screen on boot

### ISSUE THREAD

**Issue by sigxcpu76** [pecostm32/FNIRSI_1013D_Firmware#3]
I am 100% sure I've posted this earlier today but it is not here.

I followed all the steps to use your custom firmware on Daniu ADS1013 version but all I can see on boot is ~200ms of the splash screen and then the entire screen is magenta filled, nothing else.

Does that mean that the custom firmware is not compatible with the "Daniu" branded scope?

It comes with a 1GB SD card, so I tried an 8GB one but got the same result, so I guess it is not about the card size.

**Comment by pecostm32** [comment]
The card size does not matter. As long as there is enough free space starting from sector 16 to hold the code and the configuration files.

For as far as I know all these 1013 models use the same hardware, but who knows if they changed something.

You can post on EEVblog in the thread: https://www.eevblog.com/forum/testgear/fnirsi-1013d-100mhz-tablet-oscilloscope/msg4271887/#msg4271887 with some pictures of your scopes PCB so I can take a look if there are differences.

Might also help others:-)
